; Raspberry Pi Pico – Modbus RTU Slave + 2x SSD1306 + Motor GPIO
; Platform: Earle Philhower arduino-pico core (via maxgerhardt)
; Transport: Modbus RTU over USB CDC-ACM (Serial)

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board     = rpipico
framework = arduino

monitor_speed = 115200

extra_scripts = pre:get_version.py

lib_deps =
    cmb27/ModbusRTUSlave
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    adafruit/Adafruit BusIO
