; Raspberry Pi Pico – Modbus RTU Slave + 3x ST7735 + Motor GPIO
; Platform: Earle Philhower arduino-pico core (via maxgerhardt)
; Transport: Modbus RTU over USB CDC-ACM (Serial)

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board     = rpipico
framework = arduino

monitor_speed = 115200
monitor_port = /dev/ttyACM0

; USB CDC-ACM device descriptor
build_flags =
    -DUSE_TINYUSB
    -DUSBD_MANUFACTURER='"JUMO"'
    -DUSBD_PRODUCT='"JUMO Tower"'
    ; -DDEBUG  ; enable the startup delay for debug serial attachment

extra_scripts = pre:get_version.py

lib_deps =
    cmb27/ModbusRTUSlave
    adafruit/Adafruit ST7735 and ST7789 Library
    adafruit/Adafruit GFX Library
    adafruit/Adafruit BusIO
